### ISSUE TITLE
Does secondary-scheduler-operator support deploying the secondary scheduler pod only on the master node?

### ISSUE THREAD

**Issue by yanxiucai** [openshift/secondary-scheduler-operator#86]
Hi experts,

Does secondary-scheduler-operator support deploy the secondary scheduler pod only on the master node? If yes, could you please provide the Sample CR just like https://github.com/openshift/secondary-scheduler-operator/tree/master#sample-cr ?

Thanks!
Yanxiu Cai

**Comment by ingvagabund** [comment]
Based on https://github.com/openshift/secondary-scheduler-operator/blob/master/bindata/assets/secondary-scheduler/deployment.yaml there's no restriction on where a secondary scheduler runs. Also, there's currently no way to specify any additional scheduling constraints.

**Comment by yanxiucai** [comment]
Thanks @ingvagabund! Actually, I believe it is necessary to add this support. Running secondary scheduler pod on the master node would significantly improve scheduling performance.

**Comment by ingvagabund** [comment]
There are multiple aspects to consider:
- scheduling constraints: taints, node labels, affinities, topology spread constraints
- resource consumption: we currently set the resource limits to 500Mi, 100m: https://github.com/openshift/secondary-scheduler-operator/blob/master/bindata/assets/secondary-scheduler/deployment.yaml#L38-L40
- running the secondary schedulers in HA mode

Unless there's a strong customer case we do not provide new features by default. The current secondary scheduler operator makes it easier to deploy a secondary scheduler (in some default cases) without following the upstream documentation manually: https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/. We currently do not provide the same feature set as the default scheduler does since the nature of custom schedulers is unknown in advance.

**Comment by yanxiucai** [comment]
@ingvagabund  Yes, we did some performance test with running the secondary scheduler on the master node and worker node.   
When a secondary scheduler is running on the worker node, the overall time for scheduling a Pod with a Persistent Volume Claim is 40% longer than scheduling on the master node. 
Please note that everything was kept the same during the test, except for the running node of the secondary scheduler.
